services:
  api:
    container_name: ittwsd_test_api
    environment:
      - DB_NAME=ittwsd_test
      - DB_CONNECTION=mongodb://ITTWSD:ITTWSDpassword@db:27017
      - PORT=5000
    depends_on:
      - db
    tty: true
  db:
    container_name: ittwsd_test_db
    volumes:
      - "test_db:/var/lib/mongodb/data"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ITTWSD
      - MONGO_INITDB_ROOT_PASSWORD=ITTWSDpassword
      - MONGO_INITDB_DATABASE=ittwsd_test
volumes:
  test_db:
networks:
  default:
    name: ittwsd_test
